
tier1 = ["RELIANCE.NS","HDFCBANK.NS","ICICIBANK.NS","SBIN.NS","AXISBANK.NS",
"KOTAKBANK.NS","BAJFINANCE.NS","INFY.NS","TCS.NS","HCLTECH.NS",
"BHARTIARTL.NS","LT.NS","M&M.NS","MARUTI.NS","HAL.NS",
"BEL.NS","TATASTEEL.NS","JSWSTEEL.NS","ADANIPORTS.NS","SIEMENS.NS"]

tier2 = ["INDUSINDBK.NS","BANKBARODA.NS","CANBK.NS","BAJAJFINSV.NS",
"SHRIRAMFIN.NS","CHOLAFIN.NS","PFC.NS","RECLTD.NS",
"TECHM.NS","COFORGE.NS","PERSISTENT.NS","KPITTECH.NS",
"TVSMOTOR.NS","BAJAJ-AUTO.NS","EICHERMOT.NS","HEROMOTOCO.NS",
"ABB.NS","CGPOWER.NS","POLYCAB.NS","HAVELLS.NS","CUMMINSIND.NS",
"NTPC.NS","POWERGRID.NS","TATAPOWER.NS",
"DLF.NS","LODHA.NS","GODREJPROP.NS",
"RVNL.NS","IRFC.NS","RAILTEL.NS","IRCON.NS","NBCC.NS"]

tier3a = ["SUNPHARMA.NS","CIPLA.NS","DRREDDY.NS","DIVISLAB.NS","LUPIN.NS",
"ITC.NS","HINDUNILVR.NS","NESTLEIND.NS","VBL.NS","BRITANNIA.NS",
"ULTRACEMCO.NS","AMBUJACEM.NS","SRF.NS","PIIND.NS","NAVINFLUOR.NS"]

tier3b = ["ADANIENT.NS","ADANIGREEN.NS","ADANIPOWER.NS",
"BSE.NS","MCX.NS",
"PAYTM.NS","DIXON.NS","INDIGO.NS",
"SOLARINDS.NS","WAAREEENER.NS",
"MAZDOCK.NS","GRSE.NS","BDL.NS","COCHINSHIP.NS","DATAPATTNS.NS"]

tier4 = ["ONGC.NS","BPCL.NS","IOC.NS","GAIL.NS","COALINDIA.NS",
"HINDALCO.NS","JINDALSTEL.NS","NMDC.NS","VEDL.NS",
"PNB.NS","MUTHOOTFIN.NS","M&MFIN.NS",
"WIPRO.NS","MPHASIS.NS","LTIM.NS",
"MOTHERSON.NS","BHARATFORG.NS","ASHOKLEY.NS"]

core15 = ["RELIANCE.NS","HDFCBANK.NS","ICICIBANK.NS","SBIN.NS","AXISBANK.NS",
"BAJFINANCE.NS","INFY.NS","TCS.NS","BHARTIARTL.NS","LT.NS",
"M&M.NS","HAL.NS","BEL.NS","TATASTEEL.NS","ADANIPORTS.NS"]

all_tickers = tier1 + tier2 + tier3a + tier3b + tier4
print(f"Total tickers: {len(all_tickers)}, Unique: {len(set(all_tickers))}")

# We need a SECTORS dict.
# Let's map them.
sector_map = {
    "FINANCIALS": ["HDFCBANK.NS","ICICIBANK.NS","SBIN.NS","AXISBANK.NS","KOTAKBANK.NS","BAJFINANCE.NS",
                   "INDUSINDBK.NS","BANKBARODA.NS","CANBK.NS","BAJAJFINSV.NS","SHRIRAMFIN.NS","CHOLAFIN.NS","PFC.NS","RECLTD.NS",
                   "BSE.NS","MCX.NS","PAYTM.NS",
                   "PNB.NS","MUTHOOTFIN.NS","M&MFIN.NS"],
    "IT": ["INFY.NS","TCS.NS","HCLTECH.NS",
           "TECHM.NS","COFORGE.NS","PERSISTENT.NS","KPITTECH.NS",
           "WIPRO.NS","MPHASIS.NS","LTIM.NS"],
    "ENERGY": ["RELIANCE.NS",
               "NTPC.NS","POWERGRID.NS","TATAPOWER.NS",
               "ADANIENT.NS","ADANIGREEN.NS","ADANIPOWER.NS","WAAREEENER.NS",
               "ONGC.NS","BPCL.NS","IOC.NS","GAIL.NS","COALINDIA.NS"],
    "AUTO": ["M&M.NS","MARUTI.NS",
             "TVSMOTOR.NS","BAJAJ-AUTO.NS","EICHERMOT.NS","HEROMOTOCO.NS",
             "MOTHERSON.NS","BHARATFORG.NS","ASHOKLEY.NS"],
    "METALS": ["TATASTEEL.NS","JSWSTEEL.NS",
               "HINDALCO.NS","JINDALSTEL.NS","NMDC.NS","VEDL.NS"],
    "DEFENCE": ["HAL.NS","BEL.NS",
                "SOLARINDS.NS",
                "MAZDOCK.NS","GRSE.NS","BDL.NS","COCHINSHIP.NS","DATAPATTNS.NS"],
    "INDUSTRIALS": ["LT.NS","ADANIPORTS.NS","SIEMENS.NS",
                    "ABB.NS","CGPOWER.NS","POLYCAB.NS","HAVELLS.NS","CUMMINSIND.NS",
                    "RVNL.NS","IRFC.NS","RAILTEL.NS","IRCON.NS","NBCC.NS",
                    "ULTRACEMCO.NS","AMBUJACEM.NS",
                    "DIXON.NS","INDIGO.NS"],
    "REALTY": ["DLF.NS","LODHA.NS","GODREJPROP.NS"],
    "PHARMA": ["SUNPHARMA.NS","CIPLA.NS","DRREDDY.NS","DIVISLAB.NS","LUPIN.NS"],
    "FMCG": ["ITC.NS","HINDUNILVR.NS","NESTLEIND.NS","VBL.NS","BRITANNIA.NS"],
    "CHEMICALS": ["SRF.NS","PIIND.NS","NAVINFLUOR.NS"],
    "TELECOM": ["BHARTIARTL.NS"]
}

mapped_tickers = []
for k, v in sector_map.items():
    mapped_tickers.extend(v)

unmapped = set(all_tickers) - set(mapped_tickers)
print(f"Unmapped: {unmapped}")

