"""
core/universe.py
================
Single source of truth for the curated NSE ticker universe and sector mapping.
Previously embedded in screener.py; extracted so core/ modules can import
it without pulling in the monolith.
"""

from __future__ import annotations

# ==========================================
# TIER DEFINITIONS (Sovereign Scanning Tiers)
# ==========================================

TIER_1_GENERALS = [
    "RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS",
    "KOTAKBANK.NS", "BAJFINANCE.NS", "INFY.NS", "TCS.NS", "HCLTECH.NS",
    "BHARTIARTL.NS", "LT.NS", "M&M.NS", "MARUTI.NS", "HAL.NS", "BEL.NS",
    "TATASTEEL.NS", "JSWSTEEL.NS", "ADANIPORTS.NS", "SIEMENS.NS"
]

TIER_2_ROTATION = [
    "INDUSINDBK.NS", "BANKBARODA.NS", "CANBK.NS", "BAJAJFINSV.NS", "SHRIRAMFIN.NS",
    "CHOLAFIN.NS", "PFC.NS", "RECLTD.NS", "TECHM.NS", "COFORGE.NS", "PERSISTENT.NS",
    "KPITTECH.NS", "TVSMOTOR.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "ABB.NS", "CGPOWER.NS", "POLYCAB.NS", "HAVELLS.NS", "CUMMINSIND.NS", "NTPC.NS",
    "POWERGRID.NS", "TATAPOWER.NS", "DLF.NS", "LODHA.NS", "GODREJPROP.NS", "RVNL.NS",
    "IRFC.NS", "RAILTEL.NS", "IRCON.NS", "NBCC.NS"
]

TIER_3A_DEFENSIVE = [
    "SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "LUPIN.NS", "ITC.NS",
    "HINDUNILVR.NS", "NESTLEIND.NS", "VBL.NS", "BRITANNIA.NS", "ULTRACEMCO.NS",
    "AMBUJACEM.NS", "SRF.NS", "PIIND.NS", "NAVINFLUOR.NS"
]

TIER_3B_EVENT = [
    "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "BSE.NS", "MCX.NS", "PAYTM.NS",
    "DIXON.NS", "INDIGO.NS", "SOLARINDS.NS", "WAAREEENER.NS", "MAZDOCK.NS", "GRSE.NS",
    "BDL.NS", "COCHINSHIP.NS", "DATAPATTNS.NS"
]

TIER_4_MACRO = [
    "ONGC.NS", "BPCL.NS", "IOC.NS", "GAIL.NS", "COALINDIA.NS", "HINDALCO.NS",
    "JINDALSTEL.NS", "NMDC.NS", "VEDL.NS", "PNB.NS", "MUTHOOTFIN.NS", "M&MFIN.NS",
    "WIPRO.NS", "MPHASIS.NS", "LTIM.NS", "MOTHERSON.NS", "BHARATFORG.NS",
    "ASHOKLEY.NS"
]

TIER_5_BROAD_500 = [
    "CUPID.NS", "STLTECH.NS", "MTARTECH.NS", "SWANDEF.NS", "HFCL.NS", "ATHERENERG.NS",
    "WELCORP.NS", "SANSERA.NS", "CPPLUS.NS", "AVALON.NS", "HAPPYFORGE.NS",
    "KIRLOSENG.NS", "THANGAMAYL.NS", "GRWRHITECH.NS", "DIACABS.NS", "APARINDS.NS",
    "SHILPAMED.NS", "TMB.NS", "AETHER.NS", "IDEA.NS", "ACUTAAS.NS", "LAURUSLABS.NS",
    "HINDCOPPER.NS", "CHENNPETRO.NS", "BHEL.NS", "MARKSANS.NS", "RRKABEL.NS",
    "PFOCUS.NS", "SYRMA.NS", "IFCI.NS", "ARVIND.NS", "INOXINDIA.NS", "WELSPUNLIV.NS",
    "ADANIENSOL.NS", "SAILIFE.NS", "CEMPRO.NS", "AZAD.NS", "LUMAXTECH.NS",
    "FEDERALBNK.NS", "SONACOMS.NS", "AEGISLOG.NS", "PTCIL.NS", "SHRIPISTON.NS",
    "BBOX.NS", "NATIONALUM.NS", "ASTRAMICRO.NS", "GRANULES.NS", "POWERINDIA.NS",
    "BELRISE.NS", "NETWEB.NS", "KARURVYSYA.NS", "CRAFTSMAN.NS", "MAHABANK.NS",
    "REDINGTON.NS", "RADICO.NS", "AUROPHARMA.NS", "CUB.NS", "GVT&D.NS",
    "NEULANDLAB.NS", "GLAND.NS", "HONASA.NS", "JINDALSAW.NS", "SHAILY.NS", "AUBANK.NS",
    "ANANDRATHI.NS", "ALIVUS.NS", "RBLBANK.NS", "IIFL.NS", "NAM-INDIA.NS", "CGCL.NS",
    "PNBHOUSING.NS", "WOCKPHARMA.NS", "PRIVISCL.NS", "HSCL.NS", "IPCALAB.NS",
    "J&KBANK.NS", "UNIONBANK.NS", "JBCHEPHARM.NS", "SAIL.NS", "VTL.NS", "FINCABLES.NS",
    "BLUESTONE.NS", "ABCAPITAL.NS", "OFSS.NS", "GESHIP.NS", "NUVAMA.NS", "SCI.NS",
    "EMCURE.NS", "ACMESOLAR.NS", "LLOYDSME.NS", "GRAPHITE.NS", "AIAENG.NS",
    "MINDACORP.NS", "ENGINERSIN.NS", "TORNTPHARM.NS", "NYKAA.NS", "MRPL.NS",
    "TITAN.NS", "LTF.NS", "VIJAYA.NS", "FLUOROCHEM.NS", "ELGIEQUIP.NS",
    "AJANTPHARM.NS", "NAZARA.NS", "SCHNEIDER.NS", "HINDZINC.NS", "APLAPOLLO.NS",
    "APOLLO.NS", "THELEELA.NS", "ANGELONE.NS", "CAPLIPOINT.NS", "USHAMART.NS",
    "INDIANB.NS", "LMW.NS", "AARTIIND.NS", "BALRAMCHIN.NS", "STARHEALTH.NS",
    "BANKINDIA.NS", "ABSLAMC.NS", "PHOENIXLTD.NS", "PRUDENT.NS", "INGERRAND.NS",
    "ASTERDM.NS", "HATSUN.NS", "OIL.NS", "GRINDWELL.NS", "CARTRADE.NS",
    "AGARWALEYE.NS", "ZENTEC.NS", "MOTILALOFS.NS", "AEGISVOPAK.NS", "ABDL.NS",
    "CCL.NS", "GLENMARK.NS", "ANANTRAJ.NS", "IDFCFIRSTB.NS", "NIACL.NS",
    "SUNDRMFAST.NS", "NLCINDIA.NS", "ASAHIINDIA.NS", "GRASIM.NS", "KALYANKJIL.NS",
    "BOSCHLTD.NS", "LALPATHLAB.NS", "TATATECH.NS", "KPRMILL.NS", "CARBORUNIV.NS",
    "SHYAMMETL.NS", "KEI.NS", "TI.NS", "MANAPPURAM.NS", "ZYDUSWELL.NS", "ZYDUSLIFE.NS",
    "JYOTICNC.NS", "GABRIEL.NS", "OBEROIRLTY.NS", "IKS.NS", "SAMMAANCAP.NS",
    "TVSHLTD.NS", "KPIL.NS", "ANTHEM.NS", "APOLLOHOSP.NS", "TATACOMM.NS",
    "GMRAIRPORT.NS", "INDUSTOWER.NS", "TRITURBINE.NS", "ANURAS.NS", "RATNAMANI.NS",
    "TBOTEK.NS", "JSWINFRA.NS", "MARICO.NS", "THERMAX.NS", "UNITDSPR.NS", "YESBANK.NS",
    "360ONE.NS", "GMDCLTD.NS", "PPLPHARMA.NS", "3MINDIA.NS", "NSLNISP.NS", "TIMKEN.NS",
    "BIOCON.NS", "NH.NS", "SAGILITY.NS", "BOSCH-HCIL.NS", "GLAXO.NS", "INDGN.NS",
    "CREDITACC.NS", "PETRONET.NS", "POONAWALLA.NS", "FINEORG.NS", "SCHAEFFLER.NS",
    "ACE.NS", "JSWENERGY.NS", "PCJEWELLER.NS", "SUNDARMFIN.NS", "EXIDEIND.NS",
    "ASTRAL.NS", "KIMS.NS", "SPLPETRO.NS", "BEML.NS", "PRESTIGE.NS", "ATGL.NS",
    "IDBI.NS", "PIDILITIND.NS", "LTFOODS.NS", "TORNTPOWER.NS", "MEDANTA.NS", "PGEL.NS",
    "BANDHANBNK.NS", "GPIL.NS", "FORCEMOT.NS", "HONAUT.NS", "ATUL.NS", "JBMA.NS",
    "KAJARIACER.NS", "LICHSGFIN.NS", "CEATLTD.NS", "BRIGADE.NS", "LINDEINDIA.NS",
    "BALKRISIND.NS", "PREMIERENE.NS", "FIVESTAR.NS", "POLICYBZR.NS", "NATCOPHARM.NS",
    "ALKEM.NS", "TRAVELFOOD.NS", "NHPC.NS", "KSB.NS", "JSL.NS", "ETERNAL.NS",
    "CIEINDIA.NS", "RAINBOW.NS", "ASIANPAINT.NS", "DELHIVERY.NS", "NAUKRI.NS",
    "GODREJIND.NS", "MFSL.NS", "CAMS.NS", "CHOICEIN.NS", "FORTIS.NS", "SBILIFE.NS",
    "DEEPAKFERT.NS", "UNOMINDA.NS", "CRISIL.NS", "CASTROLIND.NS", "AMBER.NS",
    "NIVABUPA.NS", "GICRE.NS", "CESC.NS", "TATACONSUM.NS", "JSWDULUX.NS",
    "DEEPAKNTR.NS", "LICI.NS", "AADHARHFC.NS", "ENDURANCE.NS", "HINDPETRO.NS",
    "CONCOR.NS", "TATAINVEST.NS", "CDSL.NS", "INDHOTEL.NS", "CENTURYPLY.NS",
    "KIRLOSBROS.NS", "IGIL.NS", "ENRIN.NS", "IRB.NS", "MANKIND.NS", "SARDAEN.NS",
    "BERGEPAINT.NS", "PFIZER.NS", "TIINDIA.NS", "VGUARD.NS", "GALLANTT.NS", "HDBFS.NS",
    "CHALET.NS", "SOBHA.NS", "JUBLPHARMA.NS", "ECLERX.NS", "CENTRALBK.NS", "ITI.NS",
    "BHARTIHEXA.NS", "COROMANDEL.NS", "HDFCAMC.NS", "APOLLOTYRE.NS", "CONCORDBIO.NS",
    "MRF.NS", "HYUNDAI.NS", "CHOLAHLDNG.NS", "IOB.NS", "SUMICHEM.NS", "LTM.NS",
    "UCOBANK.NS", "SBICARD.NS", "KFINTECH.NS", "MAXHEALTH.NS", "BAJAJHLDNG.NS",
    "NTPCGREEN.NS", "APLLTD.NS", "AFFLE.NS", "GSPL.NS", "KIOCL.NS", "AIIL.NS",
    "POLYMED.NS", "ABBOTINDIA.NS", "HUDCO.NS", "DOMS.NS", "UPL.NS", "ONESOURCE.NS",
    "LTTS.NS", "ARE&M.NS", "NAVA.NS", "MSUMI.NS", "MAHSCOOTER.NS", "HBLENGINE.NS",
    "BASF.NS", "RAMCOCEM.NS", "VOLTAS.NS", "SUNTV.NS", "DCMSHRIRAM.NS", "JSWCEMENT.NS",
    "ICICIGI.NS", "MANYAVAR.NS", "PAGEIND.NS", "PSB.NS", "ESCORTS.NS", "FACT.NS",
    "VENTIVE.NS", "KANSAINER.NS", "ICICIPRULI.NS", "SUZLON.NS", "PARADEEP.NS",
    "SUPREMEIND.NS", "BAYERCROP.NS", "SHREECEM.NS", "IREDA.NS", "DMART.NS",
    "DEVYANI.NS", "BLUESTARCO.NS", "ERIS.NS", "ABREL.NS", "VINATIORGA.NS", "TRENT.NS",
    "JKCEMENT.NS", "METROBRAND.NS", "JIOFIN.NS", "CHAMBLFERT.NS", "ASTRAZEN.NS",
    "BAJAJHFL.NS", "COLPAL.NS", "FSL.NS", "IGL.NS", "BIKAJI.NS", "HEXT.NS",
    "GODIGIT.NS", "JUBLFOOD.NS", "AWL.NS", "EIHOTEL.NS", "DALBHARAT.NS", "SJVN.NS",
    "UBL.NS", "GILLETTE.NS", "CROMPTON.NS", "HDFCLIFE.NS", "GODREJCP.NS",
    "EIDPARRY.NS", "ACC.NS", "DABUR.NS", "VMM.NS", "IRCTC.NS", "TATACHEM.NS",
    "ITCHOTELS.NS", "TATAELXSI.NS", "OLAELEC.NS", "SWIGGY.NS", "EMAMILTD.NS",
    "SYNGENE.NS", "PATANJALI.NS", "PGHH.NS", "GODFRYPHLP.NS", "KAYNES.NS",
    "INOXWIND.NS", "COHANCE.NS", "TMPV.NS", "TMCV.NS", "TATACAP.NS", "ICICIAMC.NS",
    "GROWW.NS", "LENSKART.NS", "LGEINDIA.NS", "MEESHO.NS", "PIRAMALFIN.NS", "PWL.NS",
    "RUBICON.NS", "URBANCO.NS", "EMMVEE.NS", "PINELABS.NS", "CLEANMAX.NS", "AEQUS.NS",
    "SUDEEPPHRM.NS", "SKFINDUS.NS", "ATLANTAELE.NS", "SHADOWFAX.NS", "CANHLIFE.NS",
    "FRACTAL.NS"
]

CORE_15_PULSE = [
    "RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS",
    "BAJFINANCE.NS", "INFY.NS", "TCS.NS", "BHARTIARTL.NS", "LT.NS", "M&M.NS", "HAL.NS",
    "BEL.NS", "TATASTEEL.NS", "ADANIPORTS.NS"
]

TIERS: dict[str, list[str]] = {
    "tier1": TIER_1_GENERALS,
    "tier2": TIER_2_ROTATION,
    "tier3a": TIER_3A_DEFENSIVE,
    "tier3b": TIER_3B_EVENT,
    "tier4": TIER_4_MACRO,
    "tier5": TIER_5_BROAD_500,
    "core15": CORE_15_PULSE,
    "core100": (
        TIER_1_GENERALS
        + TIER_2_ROTATION
        + TIER_3A_DEFENSIVE
        + TIER_3B_EVENT
        + TIER_4_MACRO
    ),
    "all": [],  # Populated below once ALL_TICKERS is defined
}

# ==========================================
# SECTOR MAPPINGS
# (Used by Scoring/Gate-Check layer for weights)
# ==========================================

SECTORS: dict[str, list[str]] = {
    "FINANCIALS": [
        "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS", "KOTAKBANK.NS",
        "BAJFINANCE.NS", "INDUSINDBK.NS", "BANKBARODA.NS", "CANBK.NS", "BAJAJFINSV.NS",
        "SHRIRAMFIN.NS", "CHOLAFIN.NS", "PFC.NS", "RECLTD.NS", "BSE.NS", "MCX.NS",
        "PAYTM.NS", "PNB.NS", "MUTHOOTFIN.NS", "M&MFIN.NS", "TMB.NS", "IFCI.NS",
        "FEDERALBNK.NS", "KARURVYSYA.NS", "MAHABANK.NS", "CUB.NS", "AUBANK.NS",
        "ANANDRATHI.NS", "RBLBANK.NS", "IIFL.NS", "NAM-INDIA.NS", "CGCL.NS",
        "PNBHOUSING.NS", "J&KBANK.NS", "UNIONBANK.NS", "ABCAPITAL.NS", "NUVAMA.NS",
        "LTF.NS", "ANGELONE.NS", "INDIANB.NS", "STARHEALTH.NS", "BANKINDIA.NS",
        "ABSLAMC.NS", "PRUDENT.NS", "MOTILALOFS.NS", "IDFCFIRSTB.NS", "NIACL.NS",
        "MANAPPURAM.NS", "SAMMAANCAP.NS", "YESBANK.NS", "360ONE.NS", "CREDITACC.NS",
        "POONAWALLA.NS", "SUNDARMFIN.NS", "IDBI.NS", "BANDHANBNK.NS", "LICHSGFIN.NS",
        "FIVESTAR.NS", "POLICYBZR.NS", "MFSL.NS", "CAMS.NS", "CHOICEIN.NS",
        "SBILIFE.NS", "CRISIL.NS", "NIVABUPA.NS", "GICRE.NS", "LICI.NS",
        "AADHARHFC.NS", "TATAINVEST.NS", "CDSL.NS", "HDBFS.NS", "CENTRALBK.NS",
        "HDFCAMC.NS", "CHOLAHLDNG.NS", "IOB.NS", "UCOBANK.NS", "SBICARD.NS",
        "KFINTECH.NS", "BAJAJHLDNG.NS", "AIIL.NS", "HUDCO.NS", "MAHSCOOTER.NS",
        "ICICIGI.NS", "PSB.NS", "ICICIPRULI.NS", "IREDA.NS", "JIOFIN.NS",
        "BAJAJHFL.NS", "GODIGIT.NS", "HDFCLIFE.NS", "TATACAP.NS", "ICICIAMC.NS",
        "GROWW.NS", "PIRAMALFIN.NS", "PINELABS.NS", "CANHLIFE.NS"
    ],
    "IT": [
        "INFY.NS", "TCS.NS", "HCLTECH.NS", "TECHM.NS", "COFORGE.NS", "PERSISTENT.NS",
        "KPITTECH.NS", "WIPRO.NS", "MPHASIS.NS", "LTIM.NS", "BBOX.NS", "NETWEB.NS",
        "REDINGTON.NS", "OFSS.NS", "NAZARA.NS", "CARTRADE.NS", "TATATECH.NS", "IKS.NS",
        "TBOTEK.NS", "SAGILITY.NS", "INDGN.NS", "NAUKRI.NS", "ECLERX.NS", "LTM.NS",
        "AFFLE.NS", "LTTS.NS", "FSL.NS", "HEXT.NS", "TATAELXSI.NS", "PWL.NS",
        "URBANCO.NS", "FRACTAL.NS"
    ],
    "ENERGY": [
        "RELIANCE.NS", "NTPC.NS", "POWERGRID.NS", "TATAPOWER.NS", "ADANIENT.NS",
        "ADANIGREEN.NS", "ADANIPOWER.NS", "WAAREEENER.NS", "ONGC.NS", "BPCL.NS",
        "IOC.NS", "GAIL.NS", "COALINDIA.NS", "CHENNPETRO.NS", "ADANIENSOL.NS",
        "AEGISLOG.NS", "GESHIP.NS", "ACMESOLAR.NS", "MRPL.NS", "OIL.NS",
        "AEGISVOPAK.NS", "NLCINDIA.NS", "PETRONET.NS", "JSWENERGY.NS", "ATGL.NS",
        "TORNTPOWER.NS", "PREMIERENE.NS", "NHPC.NS", "CASTROLIND.NS", "CESC.NS",
        "HINDPETRO.NS", "NTPCGREEN.NS", "GSPL.NS", "SUZLON.NS", "IGL.NS", "SJVN.NS",
        "INOXWIND.NS", "EMMVEE.NS", "CLEANMAX.NS"
    ],
    "AUTO": [
        "M&M.NS", "MARUTI.NS", "TVSMOTOR.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS",
        "HEROMOTOCO.NS", "MOTHERSON.NS", "BHARATFORG.NS", "ASHOKLEY.NS",
        "ATHERENERG.NS", "SANSERA.NS", "HAPPYFORGE.NS", "LUMAXTECH.NS", "SONACOMS.NS",
        "SHRIPISTON.NS", "BELRISE.NS", "CRAFTSMAN.NS", "MINDACORP.NS", "SUNDRMFAST.NS",
        "ASAHIINDIA.NS", "BOSCHLTD.NS", "GABRIEL.NS", "TVSHLTD.NS", "SCHAEFFLER.NS",
        "EXIDEIND.NS", "FORCEMOT.NS", "JBMA.NS", "CEATLTD.NS", "BALKRISIND.NS",
        "CIEINDIA.NS", "UNOMINDA.NS", "ENDURANCE.NS", "TIINDIA.NS", "APOLLOTYRE.NS",
        "MRF.NS", "HYUNDAI.NS", "ARE&M.NS", "MSUMI.NS", "ESCORTS.NS", "OLAELEC.NS",
        "TMPV.NS", "TMCV.NS"
    ],
    "METALS": [
        "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "JINDALSTEL.NS", "NMDC.NS",
        "VEDL.NS", "WELCORP.NS", "HINDCOPPER.NS", "NATIONALUM.NS", "JINDALSAW.NS",
        "SAIL.NS", "LLOYDSME.NS", "HINDZINC.NS", "APLAPOLLO.NS", "USHAMART.NS",
        "SHYAMMETL.NS", "RATNAMANI.NS", "GMDCLTD.NS", "NSLNISP.NS", "GPIL.NS",
        "JSL.NS", "SARDAEN.NS", "GALLANTT.NS", "KIOCL.NS", "NAVA.NS"
    ],
    "DEFENCE": [
        "HAL.NS", "BEL.NS", "SOLARINDS.NS", "MAZDOCK.NS", "GRSE.NS", "BDL.NS",
        "COCHINSHIP.NS", "DATAPATTNS.NS", "MTARTECH.NS", "SWANDEF.NS", "AZAD.NS",
        "PTCIL.NS", "ASTRAMICRO.NS", "APOLLO.NS", "ZENTEC.NS", "BEML.NS", "AEQUS.NS"
    ],
    "INDUSTRIALS": [
        "LT.NS", "ADANIPORTS.NS", "SIEMENS.NS", "ABB.NS", "CGPOWER.NS", "POLYCAB.NS",
        "HAVELLS.NS", "CUMMINSIND.NS", "RVNL.NS", "IRFC.NS", "RAILTEL.NS", "IRCON.NS",
        "NBCC.NS", "ULTRACEMCO.NS", "AMBUJACEM.NS", "DIXON.NS", "INDIGO.NS",
        "CPPLUS.NS", "AVALON.NS", "KIRLOSENG.NS", "DIACABS.NS", "APARINDS.NS",
        "BHEL.NS", "RRKABEL.NS", "PFOCUS.NS", "SYRMA.NS", "ARVIND.NS", "INOXINDIA.NS",
        "WELSPUNLIV.NS", "CEMPRO.NS", "POWERINDIA.NS", "GVT&D.NS", "SHAILY.NS",
        "VTL.NS", "FINCABLES.NS", "SCI.NS", "GRAPHITE.NS", "AIAENG.NS",
        "ENGINERSIN.NS", "ELGIEQUIP.NS", "SCHNEIDER.NS", "THELEELA.NS", "LMW.NS",
        "INGERRAND.NS", "GRINDWELL.NS", "GRASIM.NS", "KPRMILL.NS", "CARBORUNIV.NS",
        "KEI.NS", "JYOTICNC.NS", "KPIL.NS", "GMRAIRPORT.NS", "TRITURBINE.NS",
        "JSWINFRA.NS", "THERMAX.NS", "3MINDIA.NS", "TIMKEN.NS", "BOSCH-HCIL.NS",
        "ACE.NS", "ASTRAL.NS", "PGEL.NS", "HONAUT.NS", "KAJARIACER.NS",
        "TRAVELFOOD.NS", "KSB.NS", "ETERNAL.NS", "DELHIVERY.NS", "AMBER.NS",
        "CONCOR.NS", "INDHOTEL.NS", "CENTURYPLY.NS", "KIRLOSBROS.NS", "IGIL.NS",
        "ENRIN.NS", "IRB.NS", "VGUARD.NS", "CHALET.NS", "HBLENGINE.NS", "RAMCOCEM.NS",
        "VOLTAS.NS", "SUNTV.NS", "JSWCEMENT.NS", "VENTIVE.NS", "SUPREMEIND.NS",
        "SHREECEM.NS", "BLUESTARCO.NS", "JKCEMENT.NS", "EIHOTEL.NS", "DALBHARAT.NS",
        "CROMPTON.NS", "ACC.NS", "IRCTC.NS", "ITCHOTELS.NS", "KAYNES.NS",
        "LGEINDIA.NS", "SKFINDUS.NS", "ATLANTAELE.NS", "SHADOWFAX.NS"
    ],
    "REALTY": [
        "DLF.NS", "LODHA.NS", "GODREJPROP.NS", "PHOENIXLTD.NS", "ANANTRAJ.NS",
        "OBEROIRLTY.NS", "PRESTIGE.NS", "BRIGADE.NS", "SOBHA.NS", "ABREL.NS"
    ],
    "PHARMA": [
        "SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "LUPIN.NS",
        "SHILPAMED.NS", "LAURUSLABS.NS", "MARKSANS.NS", "SAILIFE.NS", "GRANULES.NS",
        "AUROPHARMA.NS", "NEULANDLAB.NS", "GLAND.NS", "ALIVUS.NS", "WOCKPHARMA.NS",
        "IPCALAB.NS", "JBCHEPHARM.NS", "EMCURE.NS", "TORNTPHARM.NS", "VIJAYA.NS",
        "AJANTPHARM.NS", "CAPLIPOINT.NS", "ASTERDM.NS", "AGARWALEYE.NS", "GLENMARK.NS",
        "LALPATHLAB.NS", "ZYDUSLIFE.NS", "ANTHEM.NS", "APOLLOHOSP.NS", "PPLPHARMA.NS",
        "BIOCON.NS", "NH.NS", "GLAXO.NS", "KIMS.NS", "MEDANTA.NS", "NATCOPHARM.NS",
        "ALKEM.NS", "RAINBOW.NS", "FORTIS.NS", "MANKIND.NS", "PFIZER.NS",
        "JUBLPHARMA.NS", "CONCORDBIO.NS", "MAXHEALTH.NS", "APLLTD.NS", "POLYMED.NS",
        "ABBOTINDIA.NS", "ONESOURCE.NS", "ERIS.NS", "ASTRAZEN.NS", "SYNGENE.NS",
        "COHANCE.NS", "RUBICON.NS", "SUDEEPPHRM.NS"
    ],
    "FMCG": [
        "ITC.NS", "HINDUNILVR.NS", "NESTLEIND.NS", "VBL.NS", "BRITANNIA.NS",
        "CUPID.NS", "THANGAMAYL.NS", "RADICO.NS", "HONASA.NS", "BLUESTONE.NS",
        "NYKAA.NS", "TITAN.NS", "BALRAMCHIN.NS", "HATSUN.NS", "ABDL.NS", "CCL.NS",
        "KALYANKJIL.NS", "TI.NS", "ZYDUSWELL.NS", "MARICO.NS", "UNITDSPR.NS",
        "PCJEWELLER.NS", "LTFOODS.NS", "ASIANPAINT.NS", "GODREJIND.NS",
        "TATACONSUM.NS", "JSWDULUX.NS", "BERGEPAINT.NS", "DOMS.NS", "MANYAVAR.NS",
        "PAGEIND.NS", "KANSAINER.NS", "DMART.NS", "DEVYANI.NS", "TRENT.NS",
        "METROBRAND.NS", "COLPAL.NS", "BIKAJI.NS", "JUBLFOOD.NS", "AWL.NS", "UBL.NS",
        "GILLETTE.NS", "GODREJCP.NS", "EIDPARRY.NS", "DABUR.NS", "VMM.NS", "SWIGGY.NS",
        "EMAMILTD.NS", "PATANJALI.NS", "PGHH.NS", "GODFRYPHLP.NS", "LENSKART.NS",
        "MEESHO.NS"
    ],
    "CHEMICALS": [
        "SRF.NS", "PIIND.NS", "NAVINFLUOR.NS", "GRWRHITECH.NS", "AETHER.NS",
        "ACUTAAS.NS", "PRIVISCL.NS", "HSCL.NS", "FLUOROCHEM.NS", "AARTIIND.NS",
        "ANURAS.NS", "FINEORG.NS", "SPLPETRO.NS", "PIDILITIND.NS", "ATUL.NS",
        "LINDEINDIA.NS", "DEEPAKFERT.NS", "DEEPAKNTR.NS", "COROMANDEL.NS",
        "SUMICHEM.NS", "UPL.NS", "BASF.NS", "DCMSHRIRAM.NS", "FACT.NS", "PARADEEP.NS",
        "BAYERCROP.NS", "VINATIORGA.NS", "CHAMBLFERT.NS", "TATACHEM.NS"
    ],
    "TELECOM": [
        "BHARTIARTL.NS", "STLTECH.NS", "HFCL.NS", "IDEA.NS", "TATACOMM.NS",
        "INDUSTOWER.NS", "ITI.NS", "BHARTIHEXA.NS"
    ],
}

ALL_TICKERS: list[str] = list(
    dict.fromkeys(t for tickers in SECTORS.values() for t in tickers)
)
TICKER_TO_SECTOR: dict[str, str] = {
    t: s for s, tickers in SECTORS.items() for t in tickers
}

TIERS["all"] = ALL_TICKERS

N_SECTORS = len(SECTORS)
N_TICKERS = len(ALL_TICKERS)
SECTOR_LIST = list(SECTORS.keys())


def get_fyers_symbol(ticker: str) -> str:
    """Convert yfinance ticker (RELIANCE.NS) -> Fyers symbol (NSE:RELIANCE-EQ)."""
    if ":" in ticker:
        return ticker
    return f"NSE:{ticker.replace('.NS', '')}-EQ"


def fyers_to_yfi(symbol: str) -> str:
    """Convert Fyers symbol (NSE:RELIANCE-EQ) -> yfinance ticker (RELIANCE.NS)."""
    if ":" not in symbol:
        return symbol
    return f"{symbol.split(':')[1].replace('-EQ', '')}.NS"


def refresh_universe(source: str = "nse_csv") -> None:
    """
    Refresh the universe by downloading the latest indices constituents (e.g. NIFTY 500).
    Dynamically rebuilds the SECTORS and ALL_TICKERS mappings.
    This is a stub implementation meant to handle index reconstitutions.
    """
    import logging
    log = logging.getLogger("sovereign.universe")
    log.info(f"Refreshing universe from source: {source}")

    # In a real implementation, this would fetch from NSE website or a data provider,
    # parse the CSV, map industries to internal SECTORS, and update the globals.
    # We will log a warning indicating it relies on the hardcoded fallback for now.
    log.warning("Dynamic universe refresh not fully implemented; using hardcoded lists.")
